# Generated by Django 3.2.12 on 2022-03-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buss',
            new_name='Buss2',
        ),
    ]
