# Generated by Django 3.2.12 on 2022-03-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buss', models.IntegerField()),
                ('route', models.IntegerField()),
                ('passenger', models.IntegerField()),
            ],
        ),
    ]
