# Generated by Django 3.2.12 on 2022-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_alter_journey_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='passenger',
        ),
        migrations.AddField(
            model_name='journey',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
