# Generated by Django 3.2.12 on 2022-03-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('journeys', '0004_auto_20220313_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.driver'),
        ),
        migrations.AddField(
            model_name='journey',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.passenger'),
        ),
    ]
