# Generated by Django 3.2.12 on 2022-03-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0005_auto_20220313_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
